export const EGYPT_REGIONS = [
    {
        name_ar: 'القاهرة',
        name_en: 'Cairo',
        areas: [
            { name_ar: 'مدينة نصر', name_en: 'Nasr City' },
            { name_ar: 'مصر الجديدة', name_en: 'Heliopolis' },
            { name_ar: 'المعادي', name_en: 'Maadi' },
            { name_ar: 'التجمع', name_en: 'New Cairo / Tagamoa' },
            { name_ar: 'حلوان', name_en: 'Helwan' },
            { name_ar: 'وسط البلد', name_en: 'Downtown' },
            { name_ar: 'الشروق', name_en: 'El Shorouk' },
            { name_ar: 'بدر', name_en: 'Badr City' },
            { name_ar: 'أكتوبر', name_en: '6th of October' },
            { name_ar: 'الشيخ زايد', name_en: 'Sheikh Zayed' },
            { name_ar: 'مدينتي', name_en: 'Madinaty' },
            { name_ar: 'الرحاب', name_en: 'Al Rehab' },
        ]
    },
    {
        name_ar: 'الإسكندرية',
        name_en: 'Alexandria',
        areas: [
            { name_ar: 'سيدي جابر', name_en: 'Sidi Gaber' },
            { name_ar: 'سموحة', name_en: 'Smouha' },
            { name_ar: 'العجمي', name_en: 'Agami' },
            { name_ar: 'المنتزه', name_en: 'Montaza' },
            { name_ar: 'محطة الرمل', name_en: 'Mahatet El Raml' },
            { name_ar: 'لوران', name_en: 'Laurent' },
            { name_ar: 'ميامي', name_en: 'Miami' },
            { name_ar: 'كليوباترا', name_en: 'Cleopatra' },
            { name_ar: 'سبورتنج', name_en: 'Sporting' },
            { name_ar: 'السيوف', name_en: 'Asyouf' },
            { name_ar: 'استانلي', name_en: 'Stanley' },
        ]
    },
    {
        name_ar: 'الجيزة',
        name_en: 'Giza',
        areas: [
            { name_ar: 'فيصل', name_en: 'Faisal' },
            { name_ar: 'الهرم', name_en: 'Haram' },
            { name_ar: 'الدقي', name_en: 'Dokki' },
            { name_ar: 'المهندسين', name_en: 'Mohandessin' },
            { name_ar: 'أكتوبر', name_en: '6th of October' },
            { name_ar: 'الشيخ زايد', name_en: 'Sheikh Zayed' },
            { name_ar: 'العجوزة', name_en: 'Agouza' },
            { name_ar: 'حدائق الأهرام', name_en: 'Haram Gardens' },
            { name_ar: 'إمبابة', name_en: 'Imbaba' },
        ]
    },
    { name_ar: 'القليوبية', name_en: 'Qalyubia', areas: [{ name_ar: 'بنها', name_en: 'Banha' }, { name_ar: 'شبرا الخيمة', name_en: 'Shubra El Kheima' }] },
    { name_ar: 'الشرقية', name_en: 'Sharqia', areas: [{ name_ar: 'الزقازيق', name_en: 'Zagazig' }, { name_ar: 'العاشر من رمضان', name_en: '10th of Ramadan' }] },
    { name_ar: 'الغربية', name_en: 'Gharbia', areas: [{ name_ar: 'طنطا', name_en: 'Tanta' }, { name_ar: 'المحلة الكبرى', name_en: 'El Mahalla El Kubra' }] },
    { name_ar: 'المنوفية', name_en: 'Menofia', areas: [{ name_ar: 'شبين الكوم', name_en: 'Shibin El Kom' }, { name_ar: 'قويسنا', name_en: 'Quweisna' }] },
    { name_ar: 'البحيرة', name_en: 'Beheira', areas: [{ name_ar: 'دمنهور', name_en: 'Damanhur' }, { name_ar: 'كفر الدوار', name_en: 'Kafr El Dawwar' }] },
    { name_ar: 'كفر الشيخ', name_en: 'Kafr El Sheikh', areas: [{ name_ar: 'كفر الشيخ', name_en: 'Kafr El Sheikh City' }, { name_ar: 'دسوق', name_en: 'Desouk' }] },
    { name_ar: 'الدقهلية', name_en: 'Dakahlia', areas: [{ name_ar: 'المنصورة', name_en: 'Mansoura' }, { name_ar: 'ميت غمر', name_en: 'Mit Ghamr' }] },
    { name_ar: 'دمياط', name_en: 'Damietta', areas: [{ name_ar: 'دمياط', name_en: 'Damietta City' }, { name_ar: 'رأس البر', name_en: 'Ras El Bar' }] },
    { name_ar: 'بورسعيد', name_en: 'Port Said', areas: [{ name_ar: 'بورفؤاد', name_en: 'Port Fuad' }, { name_ar: 'حي الشرق', name_en: 'Al Sharq' }] },
    { name_ar: 'الإسماعيلية', name_en: 'Ismailia', areas: [{ name_ar: 'الإسماعيلية', name_en: 'Ismailia City' }, { name_ar: 'فايد', name_en: 'Fayed' }] },
    { name_ar: 'السويس', name_en: 'Suez', areas: [{ name_ar: 'السويس', name_en: 'Suez City' }, { name_ar: 'بورتوفيق', name_en: 'Port Tawfiq' }] },
    { name_ar: 'شمال سيناء', name_en: 'North Sinai', areas: [{ name_ar: 'العريش', name_en: 'Arish' }] },
    { name_ar: 'جنوب سيناء', name_en: 'South Sinai', areas: [{ name_ar: 'شرم الشيخ', name_en: 'Sharm El Sheikh' }, { name_ar: 'دهب', name_en: 'Dahab' }] },
    { name_ar: 'الفيوم', name_en: 'Fayoum', areas: [{ name_ar: 'الفيوم', name_en: 'Fayoum City' }] },
    { name_ar: 'بني سويف', name_en: 'Beni Suef', areas: [{ name_ar: 'بني سويف', name_en: 'Beni Suef City' }] },
    { name_ar: 'المنيا', name_en: 'Minya', areas: [{ name_ar: 'المنيا', name_en: 'Minya City' }] },
    { name_ar: 'أسيوط', name_en: 'Asyut', areas: [{ name_ar: 'أسيوط', name_en: 'Asyut City' }] },
    { name_ar: 'سوهاج', name_en: 'Sohag', areas: [{ name_ar: 'سوهاج', name_en: 'Sohag City' }] },
    { name_ar: 'قنا', name_en: 'Qena', areas: [{ name_ar: 'قنا', name_en: 'Qena City' }] },
    { name_ar: 'الأقصر', name_en: 'Luxor', areas: [{ name_ar: 'الأقصر', name_en: 'Luxor City' }] },
    { name_ar: 'أسوان', name_en: 'Aswan', areas: [{ name_ar: 'أسوان', name_en: 'Aswan City' }, { name_ar: 'كوم أمبو', name_en: 'Kom Ombo' }] },
    { name_ar: 'مطروح', name_en: 'Matrouh', areas: [{ name_ar: 'مرسى مطروح', name_en: 'Marsa Matrouh' }, { name_ar: 'الساحل الشمالي', name_en: 'North Coast' }] },
    { name_ar: 'البحر الأحمر', name_en: 'Red Sea', areas: [{ name_ar: 'الغردقة', name_en: 'Hurghada' }, { name_ar: 'الجونة', name_en: 'Gouna' }, { name_ar: 'سفاجا', name_en: 'Safaga' }] },
    { name_ar: 'الوادي الجديد', name_en: 'New Valley', areas: [{ name_ar: 'الخارجة', name_en: 'Kharga' }] },
];
